version: '3.7'

services:

  web:
    container_name: BINOTIFY_PREMIUM_APP
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true